TestCafe++ (#245)
* tc: updated matcher used in extractSelectorString to something that maps to a public API (less likely to change)

* tc: added filteredInternals check on extractSelectorString to prevent potential unhandled exception

* tc: dropping toEyesSelector since it is just needed for optimization - will revisit later

* tc: executeScript working with string snippets. now to see about wiring up functions too

* tc: executeScript support for strings and functions

* tc: made a helper function for looking up a TestCafe selector object and changed how it is determined

* tc: element use inside of executeScript

* tc: support both Selector and ClientFunctions in executeScript

* tc: streamlined executeScript test

* tc: moved prepareClientFunction to helpers section of file

* tc: dropped .only from executeScript test

* tc: cleanup

* tc: in prepareClientFunction, make args manipulation immutable

* tc: add todo comment and change findElements to use Selector instead of ClientFunction

* tc: updated comments in executeScript test function

* tc: updated TODO comments

* tc: added more tests for executeScript (one of them failing)

* tc: updated executeScript to support mixed data types

* tc: added a few small code comments to executeScript to convey the
intent

* tc: refactored executeScript

* tc: Added a check to the code that impliclty calls functions in
executeScript (in the ClientFunction) so that it will do so just
on Selector functions. We're unable to perform a more routine check
for this because what reaches the ClientFunction is a babelized
anonymous function. The simplest thing is to convert the function to a
string and parse it for something sensible that looks sturdy. Open to
suggestions on a better approach though.

* tc: updated the executeScript ClientFunction to use a pre-generated
function prepared outside of the ClientFunction since the script
arguments can easily be inspected and understood (versus being muddled
once inside of the ClientFunction runtime).

* tc: streamlined arg modification to a single-line

* tc: added another test case to executeScript

* tc: implemented isElement, findElement, and findElements

* tc: implemented isEqualElements

* tc: added placeholder test for takeScreenshot

* tc: flattened executeScript test helper into separate tests

* tc:
- added support for non-existent elements in findElement
- added mainContext

* tc: added script to run tests in headed mode

* tc: implemented getVisit, getUrl, and visit. Added links in code comments to the open issue/forum posts for parentContext & childContext

* tc: updated code comments

* updated deps

* tc: dropped async on functions that are sync, and fixed a bug in findElement that was preventing string selectors from being looked up

* tc: streamlined the SpecDriver tests, removing the test helper functions and inlining everything into each test

* tc: added additional skipped tests for things not yet implemented

* tc: added code comments for prepareArgsFunctionString and cleaned up unnecessary code comments

* tc: re-ordered skipped tests

* tc: added screenshots dir to gitignore (created by TestCafe)

* tc: added rimraf

* tc: implemented takeScreenshot

* tc: implemented childContext

* tc: Added support for Eyes selectors to findElement/findElements - but xpath support for findElements is lacking. An array is not getting returned from the function (just the first found element). Confirmed the function gets the correct result in the browser. Need to determine if we need this support before revisiting.

* tc: dropped build and clean per discussion with the team

* tc: dropped getWindowRect & setWindowRect in favor of moving them up into core through JS snippets

* tc: implemented getElementRect

* tc: updated comment on skipped test

* core: added fallback to refreshContexts when spec.parentContext is not implemented

* tc: implemented getWindowSize and setWindowSize here, until implemented in the core

* tc: initial coverage-test harness wiring

* tc: updated interal deps and updated coverage-test scripts to work with TestCafe

* tc: added no-op functions for build and cleanup

* tc: added explicit collection of supportedTests for tighter control

* tc: revert dep update due to error `super keyword unexpected here eyes-sdk-core/lib/sdk/EyesClassic.js:311`

* tc: simplified coverage test scripts -- dropped concurrency for now

* tc: added integration test for running with Eyes, to capture the new executeScript hurdle

* tc: Pass boundTestRun as part of declaring the ClientFunction. Fixes the integration issue with surfaced on eyes.open()

* tc: fix bug on getting the window size on headless (returns 0, 0)

* tc: added check on object reconstruction in executeScript to make sure there is a valuebefore checking its property (getContextInfo can return an entry of {selector: null})

* tc: added no-op for toEyesSelector so it won't throw in core -- this function is meant as a performance optimization, will revisit later

* tc: added script to run coverage tests headed

* tc: added test to surface bug in executeScript when processing a NodeList

* - Updated executeScript to handle NodeLists
- Updated setWindowRect to hold a sensible default

* tc: pass boundTestRun in transformSelector

* tc: expand isElement to include both Selector and DOM Node snapshots

* tc: made it so isElement just checks to see if it is a TestCafe selector (to match the contract with findElement) and made it so executeScript returns Selectors instead of DOM Node Snapshots

* tc: added support for serialized arguments to executeScript

* tc: removed old test

* tc: updates to get/setWindowRect based on feedback

* tc: updated code comments

* tc: reverted back to setting the outerWidth/outerHeight in setWindowRect since it is needed in getWindowRect -- which is called in more than one place in core. Also switched to window.resizeTo (which does not fix the issue w/ outerWidth/outerHeight but sets us up for more interesting things later

* tc: added x, y support to get/setWindowRect

* tc: current coverage test focus -- addressing issues in setting the
viewport size

* tc: updated internal deps

* dropped eyes-testcafe

* Committed with sdk-release-kit

* add eyes-testcafe to workspace

* updated internal deps

* tc: add .yarnrc file

* tc: add `@applitools/` prefix to package name

* core: bump dev dep of vg-client to latest

* tc: tl;dr -- fix for `super` keyword error.

```
yarn test:it
yarn run v1.22.5
$ testcafe chrome:headless ./test/it/*.spec.js
ERROR Cannot prepare tests due to an error.

/Users/tourdedave/_dev/eyes.sdk.javascript1/packages/eyes-sdk-core/lib/sdk/EyesClassic.js:311
        return super.checkWindowBase(
               ^^^^^

SyntaxError: 'super' keyword unexpected here
    at Object.<anonymous> (/Users/tourdedave/_dev/eyes.sdk.javascript1/packages/eyes-sdk-core/index.js:221:23)
    at Object.<anonymous> (/Users/tourdedave/_dev/eyes.sdk.javascript1/packages/eyes-testcafe/src/SpecDriver.js:1:35)
    at Object.<anonymous> (/Users/tourdedave/_dev/eyes.sdk.javascript1/packages/eyes-testcafe/test/it/SpecDriver.spec.js:2:14)
```

The `super` keyword is not supported on async class methods in the
latest stable version of Babel that is used by TestCafe. The workaround
is to call the method through prototypical inheritance.

re:
https://testcafe-discuss.devexpress.com/t/calling-super-class-async-method-from-extending-class/746
https://github.com/babel/babel/issues/3930

A proper fix for this will come out in Babel 7. So this will eventually
be something we can revert. Alternatively, there is a Babel plugin available
that applies this workaround automatically. If TestCafe adopts this
approach then we can revert this workaround sooner. Something to keep in
the back of our minds.

* tc: revert previous commit and drop eyes-testcafe from the workspace

TestCafe processes code through Babel that ends up running in strict mode,
which causes `this` to not be passed. This breaks all of the `call` commands
in the previous commit. This presented once running an e2e coverage test.

By default TestCafe does not transpile code that lives in a local
node_modules directory. But when packages are used from the hoisted
node_modules directory in the yarn workspace, it attempts to process
them with Babel. There appears to be no way to configure this behavior.
The fix is to drop this package from the workspace and link packages
as needed, or rely on what's in the public registry.

This feels like a reasonable approach since we are actively considering
dropping yarn workspaces (e.g., PR 232).

* tc: removed extra call command missed in prevous commit

* tc: switch to use TestCafe's resizeWindow

* tc: updated package.json scripts and deps

Specifically:
- dialed in running coverage tests in Docker on Chromium (to use
existing baselines)
- added explicit scripts for testing on different browsers (headless &
full - will circle back to see if there's a way to just use an env var
for this instead)
- updated to latest version of sdk-shared
- updated eyes-sdk-core to use `file:` to pick up changes for frame
traversal in EyesDriver. This was needed since yarn link won't work for
TestCafe b/c of the implicit Babeling of req'd sources outside of
node_modules, and, the Docker container won't follow the sym link (the
source needs to be in the current working directory).
- added the TestCafe Sauce plugin for future use

* tc: support collections retrieved with executeScript that contain null (e.g., getConextInfo)

* tc: update prepareArgsFunctionString to use dynamic index

* tc: update prepareArgsFunctionString to support a nested Array (e.g.,
what's provided by the setOverflow snippet)

* tc: updated supported tests based on current progress

* Page title lookup uses a Selector. When a title is not present in the
AUT, the following error is presented:

```
Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.
```

To compensate, the spec catches the error and returns an empty
string instead. Unfortunately, errors in TestCafe don't adhere to standard
calls like `error.message`, so scoping this behavior to just messages
like this is not possible.

* tc: focus on frame-in-frame cvg test

* tc: add getDriverInfo to the spec in order for appEnvironment info to get passed

* tc: added bongo scripts to package.json

* tc: added local eslint

* tc: cleaned up coverage tests scripts

* shared: add debugScreenshots option to getEyes

* tc: updated sdk-shared to use what is in mono, for simplicity

* tc: fix for Safari non-stitched region screenshots being off by one pixel

When taking a screenshot in TestCafe on Safari, the following happens:

- a 1px marker is added to the bottom of the page
- a screenshot of the entire browser window is taken
- the marker on the page is used to determine where to crop the image in order to
get a viewport screenshot

The cropping happens to swallow the 1px where the marker is -- causing
the viewport image to be 1px too short. This causes region screenshots
to be 1px off.

* tc: update specDriver to new coverage-test API for cleanup

* tc: fix off-by-one stitched region screenshots (related to: cacd176f3)

* tc: add missing function used in coverage test

* tc: use supportedTests from sdk-shared instead of specifying them explicitly

* tc: update initialization for executeScript to support fully nested arrays (e.g., 3 levels or more) -- fixes exception w/ markElements snippet

* tc: add missing hover function to the spec

* tc: fixed error in element initialization for executeScript when there are multiple elements and they are nested

* core: revert Safari 1px fix for TestCafe

* tc: fix scripts and adjust version to match the VG version of the SDK

* shared: expose coverage test config

* tc: update coverage test generation to use template

* tc: hard-coded linking

* tc: revert linking (forgot it is needed to address transpilation bug)

* tc: add file linking

* tc: add sdk name to coverage test generator

* tc: rename SpecDriver to spec-driver

* tc: fix cvg test template

* tc: update to latest tc version

* tc: initial pass on backwards compatible api for existing vg sdk

* tc: rename unit test to be consistent with src

* tc: created a translation function for converting args to a config object that can be unit tested

* tc: cleanup code comments

* tc: another code todo comment

* tc: support batch in args to config object translation

* tc: implement missing test cases for config translation

* tc: fix config translation to only set values (when setters are used) if the value is provided

* tc: add happy path checkWindow api support

* tc: add placeholder tests for checkWindow api use cases to support

* tc: add another test case for api call to support

* tc: filled in placeholder tests, skipped a couple which still need finalizing

* tc: skip unimplemented api tests and added start of translation function for eyes.checkWindow command args

* tc: add todo comments

* tc: add placeholder unit tests

* tc: implement translation for check args to check settings

* tc: fix circular ref and enable integration tests for legacy api

* tc: pass arguments in ctor and default to using the VisualGridRunner

* tc: implement remaining bits of api & tests, and a small bit of cleanup

* tc: pull in readme from other eyes-testcafe repo

* tc: a bit more cleanup, and added test for translating applitools.config.js contents to a config object

* tc: wired up applitools.config.js file loading - still need to add test for it and to finish the TODOs noted in the unit test

* tc: update legacy api test to use implicit runner and test that it is vg

* tc: add support for failTestcafeOnDiff config

* tc: persist tapDirPath to config

* tc: update todo comments

* tc: default throwEx for close to true

* tc: port custom CORS iframe test -- currently skipped since it is failing

* tc: update coverage tests scripts to use latest path and filter to just vg tests

* tc: load config in ctor & add test for it

* tc: add support for writing a tap file

* tc: update todo comments

* tc: add more todo comments

* tc: use ConfigUtils to get the applitools.config.js file

* tc: add saveDiffs: false to tests that rely on diffs

* tc: update todo comments (re: tests to port from old repo)

* tc: update deps and hard-code browser name in coverage test script

* tc: update readme

* tc: simplify test (fixes flake)

* tc: add previous testcafe versions and run scripts for them

* tc: add test for checking resource proxy issue - skipped since it is failing

* tc: add transformSelector to click

* tc: update isSelector to support internal (type) selectors

* tc: re-enable cors test & update todo comments

* tc: cleanup scripts and undo file/link for internal deps

* tc: update test name and add batching for better description (still skipped)

* tc: make dep fixed

* tc: fix coverage:sandbox and coverage:prod scripts to use coverage:generate

* tc: update deps

* tc: re-establish file link for core

* test workflow: update name and remove yarn deps (so hard-coded file/link refs for deps can be used)

* tc: add script to run just spec tests

* tc: rename src/TestCafeSDK to src/sdk

* tc: check findElements returns a length > 1

* tc: update findElements it tests to surface bug with findElements

* tc: update deps

* tc: fix findElements

* tc: refactor findElements

* tc: port over custom coverage tests that use testServer

* tc: load config when using standard eyes.open args

* tc: update custom tests to use shared applitools.config.js file that
specifies the branch name

* core, tc: add support for new concurrency model

* tc: clean up EyesFactory export

* tc: add custom tests to test:coverage script

* tc: fix require

* tc: updated the proxy resource test to use a local example

* tc: custom test cleanup

* tc: re-enable file linking for sdk-shared

* tc: set api key for custom coverage tests

* tc: skip some custom coverage tests along with notes as to why

* tc: update test details

* tc: add example to images fixture

* tc: add default export of Eyes to match what is in the legacy SDK

* tc: update readme for eyes.waitForResults

* tc: fix circular reference in css

* tc: add breakpoint

* tc: add showLogs to args translation test

* tc: update images.html to use a second image

* core, tc: use logger with correct configuration object -- fixes showLogs

The logger is created in the constructor of EyesBase using the
configuration object available at that time - which ends up being
a new instance, not the one passed with eyes.setConfiguration.

* tc: update deps & add a custom test for performance issue

* core: update changelog

* tc: update code comments in spec-driver

* tc: refactor open

* tc: fix lint config, to ignore test/generic

* tc: port typescript defs from the old sdk

* tc: remove docker

* tc: cleanup scripts

* tc: add contributing doc with notes on how to debug, other versions of TestCafe in the wild, and known limitations of the SDK

* tc: add unit test for extractSelectorString

* tc: set node engine to >= 10 since it is not specified in the old sdk and core breaks 8.9 compat with screenshotter

* tc: update deps

* tc: update deps

* tc: update index to export the same as the existing sdk

* tc: cleanup transformSelector and remove the need for extractSelectorString

* tc, shared: fix index files so both will work for the eyes-testcafe main (index-short.js) and tests (index.js). But since main is specified as index-short.js, index.js is not implicitly used when doing a require of the root dir -- so a  is added where needed to compensate

* tc: update changelog

* tc: make use of APPLITOOLS_API_KEY_SDK explicit in test:coverage:generic

* tc: implement check region by xpath test

* tc: make use of APPLITOOLS_API_KEY_SDK explicit for test:coverage script as well

* tc: file link sdk-coverage-tests

* tc: specify branch name in an env var when running coverage tests. It looks like the config specified in test-setup is getting overwritten by eyes.open

* tc: added an env var escape hatch to use a config set before open

* tc: skip relese notifications, and remove errant env var from test:coverage script

* tc: remove breakpoint from test

* tc: update trello link in test

* tc: revert skipping release notification

* tc: remove errant debugger

* bongo: add eyes-testcafe to list of supported sdks

* tc: update test - still wip

* add APPLITOOLS_SCRIPT_RESULT_MAX_BYTE_LENGTH

* tc: also include APPLITOOLS_SHOW_LOGS in logger creation

fixes it so the env var triggers logs when passed

* tc: remove spec function no longer used by core

* tc: fix getWindowRect to use windowX/windowY instead of scrollX/scrollY

* tc: removed unnecessary scroll position setting

* core: update findPathToChildContext in EyesDriver.js to fix tests and refactor. Still need to address PR comment: https://github.com/applitools/eyes.sdk.javascript1/pull/245\#discussion_r554118888

* tc: update custom coverage tests to use getEyes from sdk-shared

Co-authored-by: kyrylo <kyrylo.onufriiev@applitools.com>